name: deploy

on:
  push:
    branches:
      - '**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_NGINX: ${{ github.repository }}-nginx
  IMAGE_NAME_PHP_FPM: ${{ github.repository }}-php-fpm

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: “Rebuild .env from GitHub Secrets”
        run: |
          cat <<EOF > .env
          APP_NAME=Laravel
          APP_ENV=production
          APP_KEY=${{ secrets.APP_KEY }}
          APP_DEBUG=false
          APP_URL=https://laravel.fabbietti.it
          APP_SERVICE=php-fpm
          APP_LOCALE=en
          APP_FALLBACK_LOCALE=en
          APP_FAKER_LOCALE=en_US
          APP_MAINTENANCE_DRIVER=file
          BCRYPT_ROUNDS=12
          LOG_CHANNEL=daily
          LOG_LEVEL=warning
          DB_CONNECTION=mysql
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_DATABASE=${{ secrets.DB_DATABASE }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          SESSION_DRIVER=database
          SESSION_CONNECTION=
          SESSION_TABLE=sessions
          SESSION_LIFETIME=120
          SESSION_ENCRYPT=true
          SESSION_PATH=/
          SESSION_DOMAIN=null
          SESSION_SECURE_COOKIE=true
          SESSION_SAME_SITE=strict
          BROADCAST_CONNECTION=log
          FILESYSTEM_DISK=public
          QUEUE_CONNECTION=database
          CACHE_STORE=database
          MAIL_MAILER=smtp
          MAIL_SCHEME=${{ secrets.MAIL_SCHEME }}
          MAIL_HOST=${{ secrets.MAIL_HOST }}
          MAIL_PORT=${{ secrets.MAIL_PORT }}
          MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
          MAIL_FROM_ADDRESS=${{ secrets.MAIL_FROM_ADDRESS }}
          MAIL_FROM_NAME=${{ secrets.MAIL_FROM_NAME }}
          MAIL_EHLO_DOMAIN=${{ secrets.MAIL_EHLO_DOMAIN }}
          VITE_APP_NAME="${APP_NAME}"
          EOF

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker Nginx
        id: meta-nginx
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_NGINX }}

      - name: Extract metadata (tags, labels) for Docker PHP-FPM
        id: meta-php-fpm
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PHP_FPM }}

      - name: Build and push Docker image Nginx
        id: push-nginx
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: docker/prod/nginx/Dockerfile
          push: true
          tags: ${{ steps.meta-nginx.outputs.tags }}
          labels: ${{ steps.meta-nginx.outputs.labels }}

      - name: Build and push Docker image PHP-FPM
        id: push-php-fpm
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: docker/prod/php-fpm/Dockerfile
          push: true
          tags: ${{ steps.meta-php-fpm.outputs.tags }}
          labels: ${{ steps.meta-php-fpm.outputs.labels }}

      - name: Copy docker-compose file
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
#          fingerprint: ${{ secrets.FINGERPRINT }}
          port: ${{ secrets.PORT }}
          source: "docker-compose.prod.yml"
          target: "~/app"

      - name: Pull and deploy Docker images
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
#          fingerprint: ${{ secrets.FINGERPRINT }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/app
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d

#      - name: Generate artifact attestation for Nginx
#        uses: actions/attest-build-provenance@v2
#        with:
#          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_NGINX}}
#          subject-digest: ${{ steps.push-nginx.outputs.digest }}
#          push-to-registry: true
#
#      - name: Generate artifact attestation for PHP-FPM
#        uses: actions/attest-build-provenance@v2
#        with:
#          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PHP_FPM}}
#          subject-digest: ${{ steps.push-php-fpm.outputs.digest }}
#          push-to-registry: true
